version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  apt_packages:
    - maven
    - openjdk-25-jdk
  jobs:
    pre_build:
      - mvn openapi:documentation -Dmaven.test.skip=true
python:
  install:
    - method: pip
      path: ./docs/

sphinx:
  configuration: docs/conf.py
