name: Verify Docker Image Can Build

# We only want to verify the docker image can be built during pull
# requests; there's no reason to check every push.
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image (without publish)
      uses: docker/build-push-action@v3
      with:
        context: .